name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3']
        phpunit-versions: ['latest']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: intl
          tools: phpunit:${{ matrix.phpunit-versions }}
      - name: Composer install
        run: composer install --prefer-dist

      - name: Run PHPUnit (8.1)
        run: php8.1 vendor/bin/phpunit

      - name: Run PHPUnit (8.2)
        run: php8.2 vendor/bin/phpunit

      - name: Run PHPUnit (8.3)
        run: php8.3 vendor/bin/phpunit
